### ISSUE TITLE
#major and #patch not working 

### ISSUE THREAD

**Issue by can-I-do** [anothrNick/github-tag-action#165]
Hey everyone,

maybe I misunderstood something, but for us the tagging via keywords in the commit message is not working. It always does the default (minor) increment of the patch.

Another thing is, if you already have a tag like `v1.0` it is not creating the initial tag, instead it is creating a `v.` without numbers.

![CleanShot 2022-07-29 at 08 54 18](https://user-images.githubusercontent.com/60129163/181701246-adda63d8-5052-44e8-9ee3-c9ec365bd3b9.png)

**Comment by DeepCowProductions** [comment]
Same here. It also appears to just completely ignore #minor #major #patch in the commit messages.

**Comment by zozoxo1** [comment]
https://github.com/fhswf/JupyterHub-Autotagger-Action/tree/v1.0.3 we fixed this issue by checking if the with_v variable is set. You can use our release if you want.

**Comment by pacroy** [comment]
As workaround, I switched back to `1.36.0` as these tags are still working fine.

**Comment by sbe-arg** [comment]
https://github.com/anothrNick/github-tag-action/pull/157

**Comment by sammcj** [comment]
This should be resolved now, if not let me know and I'll reopen.

**Comment by dgokcin** [comment]
@sammcj I think the issue is still present. I created a new issue in #207
